server:
  port: 8888
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 1234567
    url: jdbc:mysql://localhost:3306/testmis81?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
mybatis:
  configuration:
    map-underscore-to-camel-case: true    #将_转为驼峰命名
mapper:
  identity: MYSQL   # 标识列用mysql  配置主键自动增长
logging:
  level:
    com.yc.springcloud_2: debug

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: microservice-provider-product_1   #实例名
    lease-expiration-duration-in-seconds: 90  #如果现在超过了5s的时间间隔( default: 90 s )
    lease-renewal-interval-in-seconds: 30   #设置心跳的时间间隔( default:30s )
#监控配置
info:
  app.name: MICROSERVICE-PROVIDER
  company.name: yc
  build.artifactId: $project.artifactId$
  build.modelVersion: $project.modelVersion$